# Generated by Django 5.1.3 on 2024-11-24 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.TextField()),
                ('attribute_id', models.TextField()),
                ('timestamp', models.TextField()),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'processed_data',
            },
        ),
        migrations.AlterField(
            model_name='assetkpi',
            name='asset_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.asset'),
        ),
    ]
