# Generated by Django 5.1.3 on 2024-11-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0002_asset_alter_assetkpi_asset_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetkpi',
            name='asset_id',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
