# Generated by Django 5.1.3 on 2024-11-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0003_alter_assetkpi_asset_id_delete_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetkpi',
            name='asset_id',
            field=models.CharField(choices=[('123', '123'), ('125', '125')], max_length=255),
        ),
    ]
