# Generated by Django 5.1.3 on 2024-11-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0005_alter_assetkpi_asset_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetkpi',
            name='asset_id',
            field=models.CharField(choices=[('123', '123'), ('125', '125'), ('127', '127'), ('124', '124'), ('126', '126')], max_length=255),
        ),
    ]
